"""Added dob and profile_pic to User

Revision ID: 47ae8927d39b
Revises: 
Create Date: 2025-09-04 19:11:35.004214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ae8927d39b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.String(length=20), nullable=False, server_default='01-01-2000'))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=200), nullable=False, server_default='default.png'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
